### ISSUE TITLE
Provide a mechanism to view historical snapshots of the meeting board

### ISSUE THREAD

**Issue by jbmorley** [jbmorley/meeting#11]
We believe it may be necessary for users to view the state of the meeting board at a given point in its history (e.g., what items were on the board at 7am yesterday, ...).

The state of the board should be stored in such a way that we can retrieve this historical state, and a UI should be provided to allow users to navigate this.

_Getting this UI right seems like it could be quite difficult as simply rendering a list of each individual board state may prove extremely verbose. Perhaps a simple button is provided on the board to explicitly mark a snapshot as important and these are highlighted in such a list, perhaps a simple slider is used (slide left for historical versions, slide right for the current) to mean users don't have to explicitly see all the history, perhaps those notable snapshots could be automatically detected by guessing from the length of time a given state persisted?_

**Comment by jbmorley** [comment]
@pgryko Asked how I might go about implementing this a couple of days ago:

> What were your ideas on document storage for the project?

And my responses:

> Many of the high-availability no-sql document store type things tend to deal with versioning of documents as a sync mechanism (potentially giving you free history, etc). They also tend to trade on JSON objects for storage so that might prove a nice avenue of investigation. Things like CoughDB, etc. Most of my knowledge of this area of the world comes from a friend who works in Cloudant.
> 
> If you asked me for this feature yesterday though, I’d probably be super-lazy and store a timestamped database row for each change, containing one field with the JSON for the current complete board state. Our board state is small, meaning we’d need a LOT of changes for the database to become unmanageable. Plus, we’re already planning on sharding on boards rather than trying to perform any scaling per board. Since we rely on the server being the one source of truth so it’s safe to just write the state on any change the server receives. This way going back through history is just stepping through rows in the database and it’d be pretty easy to implement an api which asked the server to send back the state it had at a given date and you could do cute stuff like dynamic date sliders for viewing history, etc.

**Comment by pgryko** [comment]
Can you be more specific regarding sharding on boards vs scaling per board?

**Comment by jbmorley** [comment]
So I guess my idea here was that you could, if performance necessitated it, host different meetings on different node instances, potentially on different servers.

Equally, this might prove a nice unit of granularity for thinks like database stores if required.

**Comment by jbmorley** [comment]
Closing as won't fix; this initial prototype is now retired.
