### ISSUE TITLE
Application Architecture and RTC Plugins

### ISSUE THREAD

**Issue by pgryko** [jbmorley/meeting#22]
Meeting Project structure:
One of the requirements is to have custom RTC documents accessible to the meeting app.
These RTC documents could be a custom spreadsheet, document editor etc.
An architectural choice would need to be made as how to accommodate these. I see three possibilities

1) Meeting and each plugin document exist as separate projects, separately hosted. Meeting pulls in each site on a separate iframe. And each project responsible for it's own hosting and data storage. This will introduce difficulty trying to manage 100 small disparate apps.

2) Meeting and each plugin document all integrated via MVC architecture - this may run into performance issues due to the real time nature of the project. Each subsite for a plugin document is continuously ideling waiting for realtime communincation from clients. Any single blocking issue in a subsite would freeze/delay everything.

3) Meeting and plugin documents exist as two separate entities i.e. Meeting operates as an independent service and another service controls all the plugin documents.

**Comment by jbmorley** [comment]
Closing as won't fix; this initial prototype is now retired.
